# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      backend "s3" {}
      required_version = ">= 0.56.0"
    }

    provider "aws" {
      region = "us-west-2"
      assume_role {
        role_arn     = "arn:aws:iam::546962227516:role/terraform-sso"
        session_name = "terraform"
      }
      default_tags {
        tags = {
          "aws-migration-project-id" = "M78Z89KUQZ"
          "Environment"              = "production"
        }
      }
    }
